name: newcycle_code_challenge
description: Newcycle Code Challenge
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:  
  fonts:
    - family: CabinetGrotesk
      fonts:
        - asset: assets/fonts/CabinetGrotesk-Black.otf
        - asset: assets/fonts/CabinetGrotesk-Bold.otf
        - asset: assets/fonts/CabinetGrotesk-Extrabold.otf
        - asset: assets/fonts/CabinetGrotesk-Extralight.otf
        - asset: assets/fonts/CabinetGrotesk-Light.otf
        - asset: assets/fonts/CabinetGrotesk-Medium.otf
        - asset: assets/fonts/CabinetGrotesk-Regular.otf
        - asset: assets/fonts/CabinetGrotesk-Thin.otf
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
    - assets/fonts/